### ISSUE TITLE
DELETE请求如何将数组数据放在Body里面？

### ISSUE THREAD

**Issue by ZhouQQQ** [msidolphin/vue-api-creator#2]
我想传的数据格式是这样的
![image](https://user-images.githubusercontent.com/20562245/68751515-aa1c3080-063c-11ea-817e-b6550a26b034.png)

DELETE请求调用的格式
![image](https://user-images.githubusercontent.com/20562245/68752155-c5d40680-063d-11ea-9b05-96d6b2b6d096.png)

数据居然是放在query params里面的，不是payload里面
![image](https://user-images.githubusercontent.com/20562245/68752209-df754e00-063d-11ea-9bb9-87024e3e82fc.png)

用POST 同样的调用方式就没问题
![image](https://user-images.githubusercontent.com/20562245/68752964-26b00e80-063f-11ea-9af7-7c208c06ca8c.png)

**Comment by msidolphin** [comment]
在2.0.2版本中可以配置body来指定body传参，配置params指定查询字符串传参，body和params均可以为数组
```
{
  name: 'deleteTask',
  method: 'DELETE',
  path: '/xxx',
  body: true
}
```

**Comment by msidolphin** [comment]
已经四天过去了，我先暂时关闭这条issus，后续如果有问题可以再次打开
