### ISSUE TITLE
本项目如何处理前台登录问题

### ISSUE THREAD

**Issue by weiweidong1993** [msidolphin/vue-api-creator#4]
公司前台项目用的是大佬你的api-creator  后台用的是 vue-admin-element
![image](https://user-images.githubusercontent.com/53823346/69237114-e1a45300-0bcf-11ea-962e-c9e1c9c3d5e5.png)

最近在做登录这一块 然后调用接口的时候vue-admin-element用的是如下方式:

![image](https://user-images.githubusercontent.com/53823346/69237393-92125700-0bd0-11ea-9fce-c45d26016167.png)

在这个方法里面套用 this.$api(...)直接报错了:this.$api is not a function

请问有什么好的处理方法吗?

**Comment by msidolphin** [comment]
@weiweidong1993 $api方法是挂载在Vue.prototype上的，你可以采用Vue.prototype.$api的方式调用

**Comment by fengjunzixian** [comment]
大佬,关于前台登录,api-creator有什么好的实现方案吗...

**Comment by msidolphin** [comment]
@fengjunzixian 这个库只是一个封装了axios的ajax请求工具，前台登录的实现要视不同业务而定啊

**Comment by fengjunzixian** [comment]
恩恩,请继续保持更新,我和我的小伙伴一直默默支持你
