### ISSUE TITLE
如何用vue-api-creator调用接口下载文件?

### ISSUE THREAD

**Issue by weiweidong1993** [msidolphin/vue-api-creator#6]
目前用<a>标签直接拼接href可以实现文件下载,但是用api-creator就不行,返回的数据是json格式的,请问是要在this.$api里面设置吗

**Comment by msidolphin** [comment]
不清楚是什么意思，服务端返回下载地址就可以了吧？这和你如何实现下载没有关系吧

**Comment by weiweidong1993** [comment]
不用下载地址下,直接调用接口下载,后端接口如下:
![image](https://user-images.githubusercontent.com/53823346/70965885-2dadbf00-20cc-11ea-8dc0-438eca621e78.png)

前端代码如下:
![image](https://user-images.githubusercontent.com/53823346/70965956-7a919580-20cc-11ea-8569-fb387746ba45.png)

![image](https://user-images.githubusercontent.com/53823346/70965944-6fd70080-20cc-11ea-84e7-7ed3a2bb5e2a.png)

点击下载返回数据如下:
![image](https://user-images.githubusercontent.com/53823346/70966008-9b59eb00-20cc-11ea-9870-1f6132af03df.png)

![image](https://user-images.githubusercontent.com/53823346/70966029-b0367e80-20cc-11ea-8e6f-79af4d7d6df3.png)

**Comment by msidolphin** [comment]
@weiweidong1993 目前还不支持，计划在api配置中添加responseType属性（默认为json）
配置方式
```js
{
       name: 'download',
       desc: 'download',
       method: 'GET',
       path: '/download',
       responseType: 'blob'
}
```
调用
```js
// 因为原样返回服务端数据所以第三个参数要是true
this.$api('app/download', {}, true).then(data => {
      const url = window.URL.createObjectURL(new Blob([data]))
      const link = document.createElement('a')
      link.href = url
      link.setAttribute('download', 'file.png')
      document.body.appendChild(link)
      link.click()
}).catch(err => {
       console.error(err)
})
```
服务端demo（node.js）
```js
async download () {
     const filePath = 'h://微信图片_20190827145947.jpg'
     this.ctx.attachment(filePath)
     this.ctx.set('Content-Type', 'application/octet-stream')
     this.ctx.set('Access-Control-Allow-Origin', 'http://localhost:8080')
     this.ctx.set('Access-Control-Allow-Credentials', true)
     this.ctx.body= fs.createReadStream(filePath)
}
```
你看这样能不能满足需求？

**Comment by weiweidong1993** [comment]
试了一下 不太行,下载的文件打不开,而且只有15B o(╥﹏╥)o

**Comment by msidolphin** [comment]
@weiweidong1993 升级了版本吗？2.0.4的 我本地测试是可以的

**Comment by weiweidong1993** [comment]
更新以后就好啦,谢谢大佬

![image](https://user-images.githubusercontent.com/53823346/70974495-d6ffaf80-20e2-11ea-9107-5519ee3c8bc2.png)

![image](https://user-images.githubusercontent.com/53823346/70974505-dc5cfa00-20e2-11ea-8683-1b6d952818ae.png)


为大佬打call,为大佬点赞:为你唱歌~~

`为你写诗 为你静止

为你做不可能的事

为你我学会弹琴写词

为你失去理智

为你写诗 为你静止

为你做不可能的事

为你弹奏 所有情歌的句子

我忘了说 最美的是你的名字

爱情 是一种怪事

你的笑容是唯一宗旨

爱情 是一种本事

我在你心里什么位子

为你我做了太多的傻事

第一件就是为你写诗`
